;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
;; DO NOT EDIT THIS FILE DIRECTLY, EDIT README.org INSTEAD

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
(setq user-full-name "夜坂雅"
      user-mail-address "shadowrz@disroot.org")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept.
(setq doom-font (font-spec :family "Hanekokoro Mono" :width 'expanded :size 24 :weight 'regular)
      doom-variable-pitch-font (font-spec :family "Hanekokoro Sans" :size 24))

(set-fontset-font t 'han "Sarasa Mono SC")
(set-fontset-font t 'hangul "Sarasa Mono K")
(set-fontset-font t 'kana "Sarasa Mono J")
(set-fontset-font t 'cjk-misc "Sarasa Mono SC")
(set-fontset-font t nil "Sarasa Mono SC" nil 'append)

(add-to-list 'face-ignored-fonts "Hanekokoro Mono-E")
(add-to-list 'face-ignored-fonts "Hanekokoro Mono-K")

(setq confirm-kill-emacs nil)

(unless (string-match-p "/\\(ba\\|z\\|m?k\\|d?a\\)?sh$" shell-file-name)
  (let ((original-shell-file-name shell-file-name))
    (setq shell-file-name (executable-find "sh"))
    (setq-default vterm-shell original-shell-file-name)
    (setq-default explicit-shell-file-name original-shell-file-name)))

(setq doom-theme 'batppuccin-mocha)

(add-to-list 'initial-frame-alist '(fullscreen . fullboth))

(define-globalized-minor-mode
  global-mode-line-invisible-mode
  mode-line-invisible-mode
  mode-line-invisible-mode
  (redraw-display))

(global-mode-line-invisible-mode)

(setq org-directory "~/Documents/Org")

(after! org
  (setq
   org-hidden-keywords '(author date email subtitle title)))

(after! org
  (setq
   org-html-divs '((preamble "header" "preamble")
                   (content "main" "content")
                   (postamble "footer" "postamble"))))

(after! org
  (dolist (face '((org-level-1 . 2.0)
                  (org-level-2 . 1.5)
                  (org-level-3 . 1.3)
                  (org-level-4 . 1.1)
                  (org-level-5 . 1.1)
                  (org-level-6 . 1.1)
                  (org-level-7 . 1.1)
                  (org-level-8 . 1.1)))
    (set-face-attribute (car face) nil :font doom-variable-pitch-font :weight 'bold :height (cdr face))))

(after! org
  (set-face-attribute 'org-document-title nil :font doom-variable-pitch-font :weight 'bold :height 2.5))

(after! org
  (require 'org-indent)
  (after! org-indent
    (set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))))

(after! org
  (set-face-attribute 'org-block nil            :foreground nil :inherit 'fixed-pitch :height 0.85)
  (set-face-attribute 'org-code nil             :inherit '(shadow fixed-pitch) :height 0.85)
  (set-face-attribute 'org-indent nil           :inherit '(org-hide fixed-pitch) :height 0.85)
  (set-face-attribute 'org-verbatim nil         :inherit '(shadow fixed-pitch) :height 0.85)
  (set-face-attribute 'org-special-keyword nil  :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-meta-line nil        :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-checkbox nil         :inherit 'fixed-pitch))

(after! org
  (add-hook 'org-mode-hook (lambda () (display-line-numbers-mode -1)))
  (add-hook 'org-mode-hook 'variable-pitch-mode))

(setq org-roam-directory (file-name-concat org-directory "Roam"))

(setq fancy-splash-image (file-name-concat doom-user-dir "assets/doom-logo.svg"))
